### ISSUE TITLE
Remove Nth Node From End of List

### ISSUE THREAD

**Issue by vaibhavkrishanyadav** [vaibhavkrishanyadav/DSA-Resources#36]
Write a code in any language to remove the Nth node from the end of the list.

[Leetcode link](https://leetcode.com/problems/remove-nth-node-from-end-of-list/)

**Comment by raginiisingh** [comment]
Can you please assign this to me

**Comment by Kesav890** [comment]
can you please assign me this i can complete it in  c++ with linked list

**Comment by gautamV19** [comment]
Can you please assign this to me

**Comment by Yash-Goyal007** [comment]
Please assign this issue to me
