### ISSUE TITLE
Merge k Sorted Lists

### ISSUE THREAD

**Issue by vaibhavkrishanyadav** [vaibhavkrishanyadav/DSA-Resources#39]
Write a code in any language to merge k sorted lists. I will assign the issue on first come first serve basis and you will have max 2 days time to raise pr otherwise I will assign to the next one. 

[Leetcode](https://leetcode.com/problems/merge-k-sorted-lists/)

**Comment by anirudh0806** [comment]
Could you please assign this to me?

**Comment by Yash-Goyal007** [comment]
I want to work on this issue. Please assign it to me
